name: nextjs
type: 'nodejs:14'
dependencies:
  nodejs:
    yarn: "^1.22.0"
hooks:
  build: |
    yarn --frozen-lockfile
    rm .env.development
    ln -s env/.env .env
  deploy: |
    
    # API_URL_UNTRIMMED=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select (.value.id == "api") | .key')
    echo $API_URL_UNTRIMMED
    # export NEXT_PUBLIC_API_URL=$(echo "${API_URL_UNTRIMMED::-1}")
    echo $NEXT_PUBLIC_API_URL
    # printf "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL\n" > .env
    # printf "PREVIEW_SECRET=mysecret" >> .env
web:
  commands:
    start: yarn dev -- -p $PORT
disk: 512
mounts:
  /.next:
    source: local
    source_path: 'next'
  env:
    source: local
    source_path: 'env'
build:
  flavor: none
variables:
  env:
    NODE_OPTIONS: --max-old-space-size=1536
size: L
resources:
  base_memory: 1024
  memory_ratio: 1024